#!/usr/bin/env bash

# xenesis-15.2.23 (Remote Task Manager) #

# Copyright (c) 2014-2015 Antonio Cao (@burzumishi) #

# This is free software; 
# You have unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# xenesis 15.2.23 (Remote Task Manager) #

# Load xenesis Configuration Files and Setups #

# Import xenesis Main Config File #
source /opt/xenesis/etc/xenesis/xenesis.conf;

# Import xenesis Dinamic Config Files (conf.d) #
if test -d "/opt/xenesis/etc/xenesis/conf.d"; then
  CONFD=$(find /opt/xenesis/etc/xenesis/conf.d -iname "*.conf");
  for confd in $CONFD; do
    source $confd;
  done
fi;

# Import xenesis OS Config Files (os) #
case $OS in
	# Operating System # Linux, HP-UX, CYGWIN_NT, ... #
	*linux*|*Linux*|*LINUX*) source /opt/xenesis/etc/xenesis/os/linux.conf;
		;;
	*hp-ux*|*HP-UX*) source /opt/xenesis/etc/xenesis/os/hpux.conf; # TODO TODO TODO #
		;;
	*FreeBSD*|*freebsd*) source /opt/xenesis/etc/xenesis/os/freebsd.conf;
		;;
	*cygwin*|*CYGWIN*) source /opt/xenesis/etc/xenesis/os/cygwin.conf; # TODO TODO TODO #
		;;
	*) source /opt/xenesis/etc/xenesis/os/default.conf;
		;;
esac

# Load xenesis Libraries #

# Load xenesis Environment Definitions #
source /opt/xenesis/lib/libxenesis-env.la;

# Load xenesis Logger Functions #
source /opt/xenesis/lib/libxenesis-log.la;

# Load xenesis Core Functions #
source /opt/xenesis/lib/libxenesis.la;

# Load xenesis environment debug #
source /opt/xenesis/lib/libxenesis-debug.la;

# Load xenesis Basic Host & Network Functions #
source /opt/xenesis/lib/libxenesis-net.la;

# Load xenesis Remote Admin Layer (RAL) Functions #
source /opt/xenesis/lib/libxenesis-ral.la;

# Load xenesis SSH Functions #
source /opt/xenesis/lib/libxenesis-ssh.la;


# Start 'xenesis' #

main "$@";

# End 'xenesis' #
